# Generated by Django 5.1.2 on 2024-10-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
