# Generated by Django 5.1.2 on 2024-10-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comment'),
        ('users', '0003_profile_is_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('background_content', models.TextField()),
                ('teamwork_content', models.TextField()),
                ('corevalue_content', models.TextField()),
                ('team_members', models.ManyToManyField(to='users.profile')),
            ],
        ),
    ]
