# Generated by Django 5.1.2 on 2024-10-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='map',
            field=models.CharField(max_length=500),
        ),
    ]
